Know Me Better/tez/Controllers/Keşfet2Controller.cs
using Newtonsoft.Json;
using PagedList;
using tez.Controllers;
using tez.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace tez.Controllers
{
    public class Keşfet2Controller : Controller
    {
        private DbKnowMeBetterEntities db = new DbKnowMeBetterEntities();


        public ActionResult Keşfet2(string ara, int sayfa = 1)
        {
            var aranacak = from d in db.TblİşArayan select d;
            var aranacak1 = from d in db.TblİşArayan select d;


            if (!string.IsNullOrEmpty(ara))
            {

                aranacak = aranacak.Where(m => m.Ad.Contains(ara) || m.Soyad.Contains(ara));

            }

            return View(aranacak.ToList().ToPagedList(sayfa, 50));
            //return View(db.TblİşArayan.ToList());
        }

        public ActionResult Details2(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblİşArayan tblİşArayan = db.TblİşArayan.Find(id);
            if (tblİşArayan == null)
            {
                return HttpNotFound();
            }
            return View(tblİşArayan);
        }

        public ActionResult Firmalar(string ara, int sayfa = 1)
        {
            var aranacak = from d in db.Tblİşveren select d;

            if (!string.IsNullOrEmpty(ara))
            {

                aranacak = aranacak.Where(m => m.FirmaAd.Contains(ara) || m.Sektör.Contains(ara) || m.Adres.Contains(ara));

            }

            return View(aranacak.ToList().ToPagedList(sayfa, 50));

        }



        public ActionResult Details1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tblİşveren tblİşveren = db.Tblİşveren.Find(id);
            if (tblİşveren == null)
            {
                return HttpNotFound();
            }
            return View(tblİşveren);
        }

        public ActionResult İlanlar(string ara, int sayfa = 1)
        {
            var aranacak = from d in db.Tbl_İlan select d;
           


            if (!string.IsNullOrEmpty(ara))
            {

                aranacak = aranacak.Where(m => m.Baslik.Contains(ara) || m.Pozisyon.Contains(ara) || m.Adres.Contains(ara) || m.ilan_sahibi.Contains(ara));

            }
            return View(aranacak.ToList().ToPagedList(sayfa, 50));
        }

        public ActionResult İlanDet(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_İlan tblİlan = db.Tbl_İlan.Find(id);
            if (tblİlan == null)
            {
                return HttpNotFound();
            }
            return View(tblİlan);
        }
    }
}

Know Me Better/tez/Views/Keşfet2/Details1.cshtml
@model tez.Models.Tblİşveren
@{
    ViewBag.Title = "Details1";
    Layout = null;
}


<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->


<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>Conjoint a Corporate Category Bootstrap Responsive website Template | Home :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" />
    <meta name="keywords" content="Conjoint Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
	SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>

    <!-- Custom Theme files -->
    <link href="/web/css/bootstrap.css" type="text/css" rel="stylesheet" media="all">
    <link href="/web/css/style.css" type="text/css" rel="stylesheet" media="all">
    <!-- font-awesome icons -->
    <link href="/web/css/fontawesome-all.min.css" rel="stylesheet">
    <!-- //Custom Theme files -->
    <!-- online-fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">
    <!-- //online-fonts -->
</head>
<body>
    <div class="sidenav text-center">
        <div class="side_top">
            <h3>Know Me Better</h3>
            <img src="~/web/images/foto.png" alt="news image" class="img-fluid img-circle" style="width:150px; height:150px; margin-top:10px">
            <p class="banp mx-auto mt-2" style="color: aliceblue">
                <h2>@Html.DisplayFor(model => model.FirmaAd)</h2>
                <h4>@Html.DisplayFor(model => model.Sektör)</h4>
            </p>
            @*<%--<h1 class="top_hd mt-2"><a href="index.html">Conjoint</a></h1>--%>*@
            <p class="top_hdp mt-2">
                @*<asp:Repeater ID="Repeater6" runat="server">
                        <ItemTemplate>
                            <%# Eval("Unvan") %>
                        </ItemTemplate>
                    </asp:Repeater>*@
            </p>
        </div>
        <!-- header -->
        <header>
            <div class="nav-top">
                <form action="#" runat="server">
                    <nav class="mnu mx-auto">

                        <label for="drop" class="toggle">Menu</label>
                        <input type="checkbox" id="drop">
                        <ul class="menu">
                            <li><a class="btn btn-primary mt-lg-5 mt-3 agile-link-bnr" href="/Keşfet2/Firmalar/">Geri Dön</a></li>
                            <li class="mt-sm-3"><a href="#about" class="scroll">Hakkımızda</a></li>
                            <li class="mt-sm-3"><a href="#misyon" class="scroll">Misyonumuz</a></li>
                            <li class="mt-sm-3"><a href="#addres" class="scroll">Adres</a></li>
                            <li class="mt-sm-3"><a href="#contact" class="scroll">İletişim</a></li>
                           
                        </ul>
                        @*<%--<li class="btn btn-primary mt-lg-5 mt-3 agile-link-bnr" href="#" role="button">Çıkış Yap</li>--%>*@
                    </nav>
                </form>
            </div>
        </header>
        <!-- //header -->
    </div>
    <div class="main">
        @*<div class="form-control" id="home">
                <div class="container" style="width:auto; height:50px">

                    <div class="mx-auto text-left">
                        <h3>
                            Know Me Better
                        </h3>
                        <p class="banp mx-auto mt-3">

                        </p>

                    </div>
                </div>
            </div>*@
        @*<div class="form-control" id="home">
                <div class=""
            </div>*@
        <!-- about -->
        <section class="slide-wrapper" id="about">
            <h2 class="w3_head mb-4">Hakkımızda</h2>

            <p class="iner mt-md-5">

                @Html.DisplayFor(model => model.Hakkında)
            </p>

        </section>
        <!-- //about -->
        <!-- services -->
        <section class="services" id="misyon">

            <h3 class="w3_head mb-4">Misyonumuz</h3>

            <p class="iner mt-md-5">
                @Html.DisplayFor(model => model.Misyon)
            </p>

        </section>
        <!-- //services -->
        <!-- news -->
        <div class="news" id="addres">
            <h3 class="w3_head mb-4 text-left">Adres</h3>
            <p class="iner mt-md-5 text-left">
                @Html.DisplayFor(model => model.Adres)
            </p>

        </div>
        <!-- //news -->
        <!-- contact -->

        <section class="wedo" id="contact">
            <h3 class="w3_head mb-4 text-left">İletişim</h3>
            <p class="iner mt-md-5">
                @Html.DisplayFor(model => model.İletişim)
            </p>

          
        </section>
        <!-- //contact -->
    </div>

</body>
</html>

Know Me Better/tez/Views/Keşfet2/Details2.cshtml
@model tez.Models.TblİşArayan
@{
    ViewBag.Title = "Details2";
    Layout = null;
}

<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>Conjoint a Corporate Category Bootstrap Responsive website Template | Home :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" />
    <meta name="keywords" content="Conjoint Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
	SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>

    <!-- Custom Theme files -->
    <link href="/web/css/bootstrap.css" type="text/css" rel="stylesheet" media="all">
    <link href="/web/css/style.css" type="text/css" rel="stylesheet" media="all">
    <!-- font-awesome icons -->
    <link href="/web/css/fontawesome-all.min.css" rel="stylesheet">
    <!-- //Custom Theme files -->
    <!-- online-fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">
    <!-- //online-fonts -->
</head>
<body>
    <div class="sidenav text-center">
        <div class="side_top">
            <h3>Know Me Better</h3>
            <img src="~/web/images/foto.png" alt="news image" class="img-fluid img-circle" style="width:150px; height:150px; margin-top:10px">
            <p class="banp mx-auto mt-2" style="color: aliceblue">
                <h2> @Html.DisplayFor(model => model.Ad)  @Html.DisplayFor(model => model.Soyad)</h2>
                <h5> @Html.DisplayFor(model => model.KullanıcıAdı)</h5>

            </p>


        </div>
        <!-- header -->
        <header>
            <div class="nav-top">
                <form action="#" runat="server">
                    <nav class="mnu mx-auto">

                        <label for="drop" class="toggle">Menu</label>
                        <input type="checkbox" id="drop">
                        <ul class="menu">
                            <li><a class="btn btn-primary mt-md-5 mt-3 agile-link-bnr" href="/Keşfet2/Keşfet2/">Geri Dön</a></li>
                            @*<li class="active"><a href="#home" class="scroll">Ana Sayfa</a></li>*@
                            <li class="mt-sm-3"><a href="#about" class="scroll">Hakkında</a></li>
                            <li class="mt-sm-3"><a href="#edu" class="scroll">Eğitim Bilgileri</a></li>
                            <li class="mt-sm-3"><a href="#hedef" class="scroll">Hedefler</a></li>
                            <li class="mt-sm-3"><a href="#tecrube" class="scroll">Tecrübeler</a></li>
                            <li class="mt-sm-3"><a href="#yetenek" class="scroll">Yetenekler</a></li>
                            <li class="mt-sm-3"><a href="#uyelik" class="scroll">Sertifika ve Üyelikler</a></li>
                            <li class="mt-sm-3"><a href="#hobi" class="scroll">Hobiler</a></li>
                            <li class="mt-sm-3"><a href="#adres" class="scroll">Adres</a></li>
                            <li class="mt-sm-3"><a href="#contact" class="scroll">İletişim</a></li>
                           

                        </ul>

                    </nav>
                </form>
            </div>
        </header>
        <!-- //header -->
    </div>
    <div class="main">

        <section class="slide-wrapper" id="about">
            <h2 class="w3_head mb-4">Hakkında</h2>

            <p class="iner mt-md-5">

                @Html.DisplayFor(model => model.Hakkında)
            </p>

        </section>
        <!-- //about -->
        <!-- services -->
        <section class="services" id="edu">

            <h3 class="w3_head mb-4">Eğitim Bilgileri</h3>

            <p class="iner mt-md-5">
                @Html.DisplayFor(model => model.Egitim)
            </p>

        </section>
        <!-- //services -->
        <div class="news" id="hedef">
            <h3 class="w3_head mb-4 text-left">Hedefler</h3>
            <p class="iner mt-md-5 text-left">
                @Html.DisplayFor(model => model.Hedefler)
            </p>

        </div>
        <div class="news" id="tecrube">
            <h3 class="w3_head mb-4 text-left">Tecrübeler</h3>
            <p class="iner mt-md-5 text-left">
                @Html.DisplayFor(model => model.Tecrube)
            </p>

        </div>
        <div class="news" id="yetenek">
            <h3 class="w3_head mb-4 text-left">Yetenekler</h3>
            <p class="iner mt-md-5 text-left">
                <h5>Bilgisayar Yetenkleri:</h5>
                @Html.DisplayFor(model => model.Pc_yetenek)
                <br />
                <h5>Dil Yetenekleri:</h5>
                @Html.DisplayFor(model => model.Dil_yetenek)
            </p>

        </div>
        <div class="news" id="uyelik">
            <h3 class="w3_head mb-4 text-left">Sertifika ve Üyelikler</h3>
            <p class="iner mt-md-5 text-left">
                <h5>Sertifika:</h5>
                @Html.DisplayFor(model => model.Sertifika)
                <br />
                <h5>Üyelikler:</h5>
                @Html.DisplayFor(model => model.Uyelik)
            </p>

        </div>
        <div class="news" id="hobi">
            <h3 class="w3_head mb-4 text-left">Hobiler</h3>
            <p class="iner mt-md-5 text-left">
                @Html.DisplayFor(model => model.Hobiler)
            </p>

        </div>
        <!-- news -->
        <div class="news" id="adres">
            <h3 class="w3_head mb-4 text-left">Adres</h3>
            <p class="iner mt-md-5 text-left">
                @Html.DisplayFor(model => model.Adres)
            </p>

        </div>
        <!-- //news -->
        <!-- contact -->

        <section class="wedo" id="contact">
            <h3 class="w3_head mb-4 text-left">İletişim</h3>
            <p class="iner mt-md-5">
                @Html.DisplayFor(model => model.İletisim)
            </p>

          
        </section>
        <!-- //contact -->
    </div>

</body>
</html>

Know Me Better/tez/Views/Keşfet2/Firmalar.cshtml
@model IEnumerable<tez.Models.Tblİşveren>
@{
    ViewBag.Title = "Firmalar";
    Layout = Layout = "~/Views/Shared/Keşfet2.cshtml";
}

@using (@Html.BeginForm("Firmalar", "Keşfet2", FormMethod.Get))
{
    <p>
        <h3>Arama...</h3>@Html.TextBox("ara", null, new { @autocomplete = "off", @placeholder = "Arama.." })

        <button class="btn btn-primary btn-sm" type="submit" value="Ara"> <i class="glyphicon glyphicon-search"></i></button>

        <br />
    </p>
}
<br />
<table class="table table-bordered styled-table">
    <tr>
        <th>Sıra No</th>
        <th>Kullanıcı Adı</th>
        <th>Fotoğraf</th>
        <th>Firma Adı</th>
        <th>Sektör</th>
        <th>İletişim</th>
        <th>Adres</th>
        <th>Seçenekler</th>
    </tr>
    @{ int i = 0;}
    <tbody>
        @foreach (var item in Model)
        {

        <tr>
            <td>
                <div>
                    @{
                        i++;
                    }
                </div>
                @i
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KullanıcıAd)
            </td>
            <td>
                <div>
                    <div class="popup-gallery">
                        <a href="#" class="fa-street-view dropdown-item btn btn-light">
                            <img src="~/web/images/foto.png" width="50" height="50" />
                        </a><br />
                    </div>
                </div>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirmaAd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sektör)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.İletişim)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adres)
            </td>
            <td>

                @Html.ActionLink("Profile Git", "Details1", new { id = item.ID }) |
                @Html.ActionLink("İlanlar", "Firmaİlan", new { id = item.ID }) |

            </td>

        </tr>
        }
    <tbody>
</table>

Know Me Better/tez/Views/Keşfet2/Keşfet2.cshtml
@model IEnumerable<tez.Models.TblİşArayan>
@using PagedList
@using PagedList.Mvc
@using tez.Models

@{
    ViewBag.Title = "Keşfet2";
    Layout = Layout = "~/Views/Shared/Keşfet2.cshtml";
}

@using (@Html.BeginForm("Keşfet2", "Keşfet2", FormMethod.Get))
{
    <p>
        <h3>Arama...</h3>@Html.TextBox("ara", null, new { @autocomplete = "off", @placeholder = "Arama.." })

        <button class="btn btn-primary btn-sm" type="submit" value="Ara"> <i class="glyphicon glyphicon-search"></i></button>

        <br />
    </p>
}
<br />
<table class="table table-bordered styled-table">
    <tr>
        <th>Sıra No</th>
        <th>Kullanıcı Adı</th>
        <th>Fotoğraf</th>
        <th>Adı</th>
        <th>Soyadı</th>
        <th>Mail</th>
        <th>Seçenekler</th>
    </tr>

    @{ int i = 0;}
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    <div>
                        @{
                            i++;
                        }
                    </div>
                    @i
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KullanıcıAdı)
                </td>
                <td>
                    <div>
                        <div class="popup-gallery">
                            <a href="#" class="fa-street-view dropdown-item btn btn-light">
                                <img src="~/web/images/foto.png" width="50" height="50" />
                            </a><br />
                        </div>
                    </div>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Soyad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mail)
                </td>
                <td>

                    @Html.ActionLink("Profile Git", "Details2", new { id = item.ID }) |

                </td>

            </tr>
        }
    <tbody>
</table>

Know Me Better/tez/Views/Keşfet2/İlanDet.cshtml
@model tez.Models.Tbl_İlan

@{
    ViewBag.Title = "İlanDet";
    Layout = Layout = "~/Views/Shared/Keşfet2.cshtml";
}



<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            İlan Sahibi:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ilan_sahibi)
        </dd>

        <dt>
            Başlık:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            Açıklama:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Acıklama)
        </dd>

        <dt>
            Nitelikler:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nitelikler)
        </dd>

        <dt>
            Departman:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departman)
        </dd>

        <dt>
            Pozisyon:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pozisyon)
        </dd>

        <dt>
            Çalışma Şekli:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CalismaSekli)
        </dd>

        <dt>
            Tecrübe:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tecrube)
        </dd>



    </dl>
</div>
<p>

    @Html.ActionLink("Geri Dön", "İlanlar")
</p>

Know Me Better/tez/Views/Keşfet2/İlanlar.cshtml
@model IEnumerable<tez.Models.Tbl_İlan>
@{
    ViewBag.Title = "İlanlar";
    Layout = Layout = "~/Views/Shared/Keşfet2.cshtml";
}

@using (@Html.BeginForm("İlanlar", "Keşfet2", FormMethod.Get))
{
    <p>
        <h3>Arama...</h3>@Html.TextBox("ara", null, new { @autocomplete = "off", @placeholder = "Arama.." })

        <button class="btn btn-primary btn-sm" type="submit" value="Ara"> <i class="glyphicon glyphicon-search"></i></button>

        <br />
    </p>
}
<br />

<table class="table table-bordered styled-table">
    <tr>
        <th>Sıra No</th>
        <th>İlan Sahibi</th>
        <th>Başlık</th>
        <th>Pozisyon</th>
        <th>Adres</th>
        <th>Tecrübe</th>
        <th>Seçenekler</th>
    </tr>
    @{ int i = 0;}
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    <div>
                        @{
                            i++;
                        }
                    </div>
                    @i
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ilan_sahibi)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Baslik)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pozisyon)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adres)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tecrube)
                </td>
                <td>

                    @Html.ActionLink("İncele", "İlanDet", new { id = item.ID })



                </td>

            </tr>
        }
    <tbody>
</table>